ovis:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

# Trajectory Controllers ---------------------------------------
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - ovis_joint_1
      - ovis_joint_2
      - ovis_joint_3
      - ovis_joint_4
      - ovis_joint_5
      - ovis_joint_6
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.5
      ovis_joint_1:
        trajectory: 0.1
        goal: 0.5
      ovis_joint_2:
        trajectory: 0.1
        goal: 0.5
      ovis_joint_3:
        trajectory: 0.1
        goal: 0.5
      ovis_joint_4:
        trajectory: 0.1
        goal: 0.5
      ovis_joint_5:
        trajectory: 0.1
        goal: 0.5
      ovis_joint_6:
        trajectory: 0.1
        goal: 0.5

    state_publish_rate: 50


#ovis/gazebo_ros_control:  
 #   pid_gains:
 #     ovis_joint_1: {p: 100, d: 0.01, i: 0.01, i_clamp: 1}
  #    ovis_joint_2: {p: 100, d: 0.01, i: 0.01, i_clamp: 1}
   #   ovis_joint_3: {p: 100, d: 0.01, i: 0.01, i_clamp: 1}
    #  ovis_joint_4: {p: 100, d: 0.01, i: 0.01, i_clamp: 1}
     # ovis_joint_5: {p: 100, d: 0.01, i: 0.01, i_clamp: 1}
 #     ovis_joint_6: {p: 100, d: 0.01, i: 0.01, i_clamp: 1}
      

    
