manipulator:
  kinematics_solver: ovis_manipulator/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005


#kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin