jog_joint_node:
  joint_names:
    - ovis_joint_1
    - ovis_joint_2
    - ovis_joint_3
    - ovis_joint_4
    - ovis_joint_5
    - ovis_joint_6

jog_frame_node:
  group_names:
    - manipulator
  link_names:
    - ovis_link_base
    - ovis_end_effector