jog_joint_node:
  joint_names:
    - ovis_joint1
    - ovis_joint2
    - ovis_joint3
    - ovis_joint4
    - ovis_joint5
    - ovis_joint6

jog_frame_node:
  group_names:
    - manipulator
  link_names:
    - ovis_base_link
