jog_joint_node:
  joint_names:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
    - arm_joint_6

jog_frame_node:
  group_names:
    - manipulator
  link_names:
    - ovis_link_base
    - ovis_end_effector