controller_list:
  - name: fake_arm_controller
    joints:
      - ca_joint1
      - ca_joint2
      - ca_joint3
      - ca_joint4
      - ca_joint5
      - ca_joint6
  - name: fake_gripper_controller
    joints:
      - finger_joint