ovis:
  effort_joint_trajectory_controller:
    constraints:
      goal_time: 1.0
      ovis_joint_1:
        goal: 0.02
        trajectory: 0.05
      ovis_joint_2:
        goal: 0.02
        trajectory: 0.05
      ovis_joint_3:
        goal: 0.02
        trajectory: 0.05
      ovis_joint_4:
        goal: 0.02
        trajectory: 0.05
      ovis_joint_5:
        goal: 0.02
        trajectory: 0.05
      ovis_joint_6:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02
    gains:
      ovis_joint_1:
        d: 0
        i: 0
        i_clamp: 10
        p: 5000
      ovis_joint_2:
        d: 0
        i: 0
        i_clamp: 10
        p: 5000
      ovis_joint_3:
        d: 0
        i: 0
        i_clamp: 10
        p: 5000
      ovis_joint_4:
        d: 0
        i: 0
        i_clamp: 10
        p: 500
      ovis_joint_5:
        d: 0
        i: 0
        i_clamp: 10
        p: 200
      ovis_joint_6:
        d: 0
        i: 0
        i_clamp: 10
        p: 500
    joints:
    - ovis_joint_1
    - ovis_joint_2
    - ovis_joint_3
    - ovis_joint_4
    - ovis_joint_5
    - ovis_joint_6
    type: effort_controllers/JointTrajectoryController
  joint_1_position_controller:
    joint: ovis_joint_1
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointPositionController
  joint_2_position_controller:
    joint: ovis_joint_2
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointPositionController
  joint_3_position_controller:
    joint: ovis_joint_3
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointPositionController
  joint_4_position_controller:
    joint: ovis_joint_4
    pid:
      d: 0
      i: 0
      p: 500
    type: effort_controllers/JointPositionController
  joint_5_position_controller:
    joint: ovis_joint_5
    pid:
      d: 0
      i: 0
      p: 200
    type: effort_controllers/JointPositionController
  joint_6_position_controller:
    joint: ovis_joint_6
    pid:
      d: 0
      i: 0
      p: 500
    type: effort_controllers/JointPositionController
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController
