controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - ovis_joint_1
      - ovis_joint_2
      - ovis_joint_3
      - ovis_joint_4
      - ovis_joint_5
      - ovis_joint_6
initial:  # Define initial robot poses.
#  - group: manipulator
#    pose: home

  []